Add symmetric depol
quantumlib/Cirq pull request #3361
Opened 2020-09-26 00:15 UTC by tonybruguier

For issue #3220

2020-09-26 03:46 UTC, tonybruguier commented
A few remarks to the reviewer:

- I changed the check for the probability in the base class. I think I had made a mistake in my previous PR #3262 where I checked that the sum of the probabilities was a probability (i.e. between 0 and 1). In fact, the sum should be exactly 1, if I am not mistake. I thus changed the test here. The reason I noticed it is that because of numerical noise, it was adding up to 1.0000002 which failed.
- I named the new parameter 'n_qubits'. I had originally named it 'num_qubits' but it was making this test fail examples/direct_fidelity_estimation_test.py. I am not sure why. I am actually also to blame for that file, so I am happy to fix it.

Thanks for all the help so far!

2020-09-28 02:08 UTC, viathor requested changes
Thank you! Some comments below. In particular, there is a lot of comments that give an incorrect number of Pauli operators on n qubits (the code seems fine, though).

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +        all_identity = ''.join(['I'] * n_qubits)
```python
all_identity = 'I' * n_qubits
```

Also, you don't need to set this in a variable - just inline in the conditional below.

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +            if pauli_string != all_identity:
`else`

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +        for coefficients in itertools.product(['I', 'X', 'Y', 'Z'],
coefficients -> pauli_tuple

(I think most people would think that a coefficient is a number, but these are tuples of strings.)

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +            pauli_string = ''.join([g for g in coefficients])
No need for a list comprehension:

```python
pauli_string = ''.join(pauli_tuple)
```

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +        return f"D({self._p},{self._n_qubits})"
I think in a circuit diagram the number of qubits can be inferred from the number of lines this operation touches, so we don't need to include it at all.

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +        p / (2**n_qubits - 1).
4\*\*n

2020-09-28 02:08 UTC, viathor commented on cirq/ops/common_channels.py
> +        """
All quotes should be on the same line, I think (though the formatter takes precedence over my opinion!).

2020-09-28 03:06 UTC, tonybruguier commented on cirq/ops/common_channels.py
> +                    f"Probabilities do not add up to 1 but to {sum_probs}")
Added a TODO.

2020-09-28 03:24 UTC, tonybruguier commented
Thanks. PTAL.

2020-09-28 04:52 UTC, viathor approved these changes
Thank you!

2020-09-28 20:59 UTC, balopat approved these changes

2020-09-28 20:59 UTC, merged