Fix all latex expressions without enclosing $ signs
quantumlib/Cirq pull request #3407
Opened 2020-10-09 14:06 UTC by rheaparekh

Fix all latex expressions without the enclosing $ signs. Fixes issue #3286

Approach: I searched for all the raw strings in the repository, and went these strings one by one to check for missing latex expressions.

Some comments regarding specific changes to make sure they are correct:

* For file `cirq/linalg/transformations.py`: The changes would look like [this](https://hackmd.io/0UK6Na6mQ1aY2tkcEFSlxg?view).

* For file `examples/bcs_mean_field.py`: The changes would look like [this](https://hackmd.io/ZpqO-TdnQbajFo_TSRBiCA?view). I have changed the command `\dag` to `\dagger` as `\dag` wasn't being rendered properly in HackMd.

* For file `cirq/ops/common_channels.py`: Changed `$ \sum_i p_i Pi \rho Pi $` to  `$\sum_i p_i Pi \rho Pi$`, as the first expression isn't being rendered correctly in HackMd ([link](https://hackmd.io/v8_W6pXjTsqj2KuSXlJK6w?view) to view this).

2020-10-14 14:44 UTC, balopat requested changes
Thank you for combing through this! I added some comments to fix.

2020-10-14 14:44 UTC, balopat commented on examples/bcs_mean_field.py
> +$|BCS⟩ = \prod_k (u_k + v_k c^\dagger_{k,↑} c^\dagger_{−k,↓}|vac⟩$ where $|vac⟩$
Missing parenthesis: 

```suggestion
$|BCS⟩ = \prod_k (u_k + v_k c^\dagger_{k,↑} c^\dagger_{−k,↓}|vac⟩)$ where $|vac⟩$
```

2020-10-14 14:44 UTC, balopat commented on cirq/experiments/qubit_characterizations.py
> +    $c_{02} - c_{10} - c_{12} = 4*P_{00} - 1$
Let's use $$ here too

2020-10-19 09:15 UTC, rheaparekh commented
Thank you @balopat for the review. I have made the requested changes.

I also observed that I had missed the file `cirq/ops/parity_gates.py`, and I added new changes in that file.

2020-10-19 18:25 UTC, balopat approved these changes

2020-10-19 18:26 UTC, balopat commented on cirq/ops/parity_gates.py
> +    r"""The Y-parity gate, possibly raised to a power.
why the r? 
```suggestion
    """The Y-parity gate, possibly raised to a power.
```

2020-10-19 18:26 UTC, balopat commented on cirq/ops/parity_gates.py
> +    r"""The X-parity gate, possibly raised to a power.
Why the r? 
```suggestion
    """The X-parity gate, possibly raised to a power.
```

2020-10-19 22:57 UTC, balopat commented on cirq/ops/parity_gates.py
> +    r"""The X-parity gate, possibly raised to a power.
Ignore me - this is fine. raw strings are best for backslash to be interpreted as a character.

2020-10-19 23:09 UTC, merged

2020-10-20 12:49 UTC, rheaparekh commented
Thank you for the review. I am glad to have my first PR merged here!