JSON Serialization for CalibrationResult
quantumlib/Cirq pull request #3540
Opened 2020-11-26 00:09 UTC by dstrain115

- Serializes CalibrationResult dataclass
- Uses underlying Calibration serialization and datetime utc timestamp.

2020-12-01 22:01 UTC, mpharrigan approved these changes
looks good

2020-12-01 22:13 UTC, balopat requested changes
lgtm but the json test data is in the wrong place

2020-12-01 22:13 UTC, balopat commented on cirq/protocols/json_test_data/CalibrationResult.json
> +{
these should live under cirq.google.json_test_data

2020-12-03 01:04 UTC, balopat approved these changes

2020-12-05 14:47 UTC, merged