Make EqualsTester notice incorrect delegation
quantumlib/Cirq pull request #3809
Opened 2021-02-16 02:23 UTC by dabacon

This extends EqualsTester to notice when someone incorrectly does not return NotImplemented in __eq__ for objects of an unrecognized type.  Doing this can cause commutativity to fail when implementing other objects that should be equal to this object.  (It was worse in python 2, where depending on whether one inherited from object or not could cause this).

This also fixes places where Cirq code was doing this incorrectly.

Fixes #877

One final note is that the `eigen_gate_test` was changed because apparently Sympy does this incorrectly

```
>>> import sympy
>>> s = sympy.Symbol("a")
>>> class MyClass:
...   def __eq__(self, other):
...     return True
... 
>>> s.__eq__(MyClass())
False
```

2021-02-16 02:33 UTC, dabacon commented
Cirq is secretly just a test of places where Sympy fails to be pythonic?

2021-02-16 15:58 UTC, balopat commented
I just reran your checks as well on this PR to see the difference, couldn't repro the lint error yet on this branch. And now it passed. Very odd. XRef #3716.

2021-02-17 23:24 UTC, dabacon commented
@Strilanc probably the best one to look at this sense he wrote the original definition of the problem (and there seems to be a slight difference in what he said, since we don't need a fallback to reference checking to get this work).

2021-03-24 18:33 UTC, dabacon commented
@balopat this could use a triage to a reviewer

2021-03-24 21:12 UTC, 95-martin-orion requested changes
The comments in the test here are _incredibly_ helpful for parsing it, thanks!

One nit and this is good to go.

2021-03-24 22:49 UTC, dabacon commented on cirq/ops/eigen_gate_test.py
> +    eq.add_equality_group('b')
Ah yeah, they are strange.  I guess it sort of makes sense to compare to some instance of another class sometimes (to check that you did an "isinstance check"), but I think equals tester already does this. Will remove.

2021-03-24 23:03 UTC, 95-martin-orion approved these changes

2021-03-24 23:54 UTC, dabacon commented
tx @95-martin-orion !

2021-03-25 00:13 UTC, merged