Add support for Tuple[str] as measurement key in Results and measurement_key protocol
quantumlib/Cirq pull request #3968
Opened 2021-03-25 05:08 UTC by smitsanghavi

2021-03-25 17:14 UTC, 95-martin-orion requested changes
There's something bothering me about this PR, but it's difficult to pin down. I have a sense that it would be cleaner to replace all internal representations of measurement keys with `Tuple[str]` and only convert to/from strings in protocols and `MeasurementGate` construction, but I can't say how that would work (especially in a backwards-compatible way).

I think my question is this: after all of the deprecations are complete, what is the intended final state of this feature? In that state, where will string keys appear (if at all)?

2021-03-29 22:15 UTC, smitsanghavi commented
Converting this PR to draft since the design is still under discussion.

2021-03-31 20:38 UTC, daxfohl commented on cirq/ops/measurement_gate.py
> +            raise TypeError('Wrong type for measurement key. MeasurementGate only accepts str key')
Pretty sure we'd need to allow tuples here for when you flatten a circuit that has tuples produced by subcircuits. The equivalent flattened circuit would have to measure directly into the tuple.

2021-07-01 16:40 UTC, 95-martin-orion commented
Closing as discontinued. The updated design for this can be found in #4040 and the [linked RFC](https://tinyurl.com/structured-measurement-keys).

2021-07-01 16:40 UTC, closed without merging