Allow expectation values for density matrix
quantumlib/Cirq pull request #3990
Opened 2021-04-03 22:35 UTC by daxfohl

Closes #3964.

More generically, this solves it for any `SimulatesFinalState` implementation whose `TSimulationTrialResult` type implements `expectation_from_state`.

Note I don't know how to test this, however the function names and types seem to point to this being the solution.

2021-04-04 00:24 UTC, daxfohl commented
@zaqqwerty do you have a unit test I could use to check this?

2021-04-04 00:26 UTC, daxfohl commented
@tonybruguier is there a quick way to add this to MPS as well?

2021-04-04 00:29 UTC, daxfohl commented
@95-martin-orion is it possible to do the same for Clifford simulators?

2021-04-04 02:35 UTC, daxfohl commented
@95-martin-orion oops, just saw you already had a fix. Up to you whether you'd rather use this one that generifies things or stick with the yagni approach.

2021-04-04 03:22 UTC, tonybruguier commented
> @tonybruguier is there a quick way to add this to MPS as well? I see there is a state_vector field available on the trial result class. Could we add the same two lines there as I did here in state_vector_simulator and expect that to produce valid results?

I am not sure what is required. Do you want the simulator to take a density matrix as initial state and return a density matrix at the output of the circuit? That could be involved to write.

Or do you want the simulator to just output a density matrix?

2021-04-04 04:15 UTC, daxfohl commented
> I am not sure what is required. Do you want the simulator to take a density matrix as initial state and return a density matrix at the output of the circuit? That could be involved to write.

I think I figured it out. Just needed to add a way to get an expectation value from MPSTrialResult, which turned out to be a one-liner. Took the tests from density matrix simulator tests (stolen from @95-martin-orion's PR), and changed them to use MPS, and they seem to pass.

2021-04-04 21:09 UTC, daxfohl commented
Looks like Clifford also provides a function to generate a state vector from a trial result, so we can add an expectation value there too. Will add that before merging.

2021-04-05 00:24 UTC, daxfohl commented
Clifford seems to be working now too.

2021-04-05 15:10 UTC, 95-martin-orion requested changes
Regardless of how this pans out, I think we need to document the Simulator hierarchy somewhere (maybe at the top of `simulator.py`?) once it's done. Multiple nested base classes make it tricky to track which one supports what behavior.

2021-04-05 15:10 UTC, 95-martin-orion commented on cirq/sim/simulator.py
> +            swept_evs.append([result.expectation_from_state(obs) for obs in pslist])
My concern here: the fact that `expectation_from_state` has no default implementation means that `SimulatesFullState` does not fully implement `SimulatesExpectationValues`, which means user-created subclasses will have a broken API.

We could update the class docstring to say that users must implement `expectation_from_state` in their result class, but that's kind of unwieldy for a class whose base purpose does not include calculating expectation values. This is part of why I mentioned needing a `SimulatesEVsAndFullState` type for this in #3979.

2021-04-05 15:32 UTC, daxfohl commented
@95-martin-orion I agree. I think go ahead and merge your solution for density matrix. I'll look at how to improve this as time comes available.

2021-07-01 16:35 UTC, 95-martin-orion commented
Closing as superseded by #3979. There is still interest in deduplicating this behavior (#4209), but at this point it's likely easier to do so in a fresh PR. (Feel free to reopen if that's not the case.)

2021-07-01 16:35 UTC, closed without merging