CuPy-based simulator
quantumlib/Cirq pull request #4049
Opened 2021-04-23 09:19 UTC by oumjunior

CuPy-based simulator that exploits the power of GPUs and perform fast simulations especially for circuits with great width. 

The Multiplier (https://arxiv.org/pdf/1706.05113v1.pdf) execution time 
![image](https://user-images.githubusercontent.com/32430632/115849487-367f7500-a425-11eb-8cec-b0c9cb719941.png)

Supremacy circuits execution time 
![image](https://user-images.githubusercontent.com/32430632/115849333-12bc2f00-a425-11eb-9665-2949f781b144.png)

2021-04-23 09:25 UTC, oumjunior commented
@googlebot I signed it!

Le ven. 23 avr. 2021 à 11:19, google-cla[bot] ***@***.***> a
écrit :

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project (if not, look below for help).
> Before we can look at your pull request, you'll need to sign a Contributor
> License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed (or fixed any issues), please reply here with @googlebot
> I signed it! and we'll verify it.
> ------------------------------
> What to do if you already signed the CLA Individual signers
>
>    - It's possible we don't have your GitHub username or you're using a
>    different email address on your commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>
> Corporate signers
>
>    - Your company has a Point of Contact who decides which employees are
>    authorized to participate. Ask your POC to be added to the group of
>    authorized contributors. If you don't know who your Point of Contact is,
>    direct the Google project maintainer to go/cla#troubleshoot (Public
>    version <https://opensource.google/docs/cla/#troubleshoot>).
>    - The email used to register you as an authorized contributor must be
>    the email used for the Git commit. Check your existing CLA data
>    <https://cla.developers.google.com/clas> and verify that your email is
>    set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - The email used to register you as an authorized contributor must
>    also be attached to your GitHub account
>    <https://github.com/settings/emails>.
>
> ℹ️ *Googlers: Go here
> <https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fquantumlib%2FCirq%2Fpull%2F4049>
> for more info*.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/quantumlib/Cirq/pull/4049#issuecomment-825524486>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHXNUKDUSQTMU4V3FZ5MKFTTKE3SHANCNFSM43OIHJUA>
> .
>

2021-04-23 14:31 UTC, vtomole requested changes
Replacing `numpy` with `cupy` is a _huge_ change. Let's sit and think about this before we make a decision. Like i said on https://github.com/quantumlib/Cirq/issues/4045, as of now I'm not convinced that the performance improvements this change brings are worth the changes to Cirq. Maybe GPU simulation could be something that qsim handles. CC @95-martin-orion

2021-04-23 14:50 UTC, balopat commented
Hi @oumjunior, thank you for submitting this proposal. However, changing all of numpy to cupy is way too wide of a change. First of all, this change is impacting other parts of the code base like diagram drawing, qis, benchmarking, etc. which have nothing to do with simulation. Second as Victory says this might not be the place to introduce GPU support. qsim does have plans to have GPU support which will probably change the graphs. Before that happens I could _maybe_ see  creating a separate cirq module - cirq-cupy or cirq-gpu which would have a similar GPU based - however that is something to bring to the Cirq Cynque first where we can discuss whether we'd like to maintain a solution separately - given that qsim will have a GPU solution. If the verdict is none, you can still create a GPU based simulator cirq module outside of our repo and if it's well maintained we can reference it in our docs as part of our ecosystem.

2021-04-23 16:14 UTC, 95-martin-orion commented
Thanks Victory for the CC.

@oumjunior, I've added a comment to #4045 that may provide a clearer comparison with qsim.

That said, I'm interested in integrating a GPU-based simulator with Cirq regardless of its performance - I think it's a worthwhile point of reference at a minimum, and there may be specific cases where a GPU-based simulator is preferable to existing options. In lieu of a full conversion to `cupy` (which, as noted above, would require significant discussion) here's what I recommend:

- Isolate the `cupy` behavior to a new implementation of the `Simulator` interface in `cirq-core/cirq/sim/simulator.py`. The result of this would be similar to `cirq-core/cirq/sim/sparse_simulator.py`
- Open a new issue for converting Cirq to `cupy`, and join our Cirq sync (Wednesdays @ 11AM PST) to drive discussion. You can get access to the Cirq sync by joining the [cirq-dev googlegroup](https://groups.google.com/g/cirq-dev).

2021-04-23 19:44 UTC, daxfohl commented
So we don't have the number of permutations explode, would it be better to add a `use_gpu: bool` field to existing simulators rather than creating a dedicated simulator?

2021-04-27 17:48 UTC, balopat requested changes
As it is, this cannot go in. 
I'm completely open towards a GPU flag / maybe adding the ability to inject numpy implementations to simulators, but we should have a discussion about this. 
I think this is a great candidate for Cirq Cynque discussion.

2021-05-05 20:07 UTC, vtomole commented
Hey @oumjunior, please try signing the CLA again. It looks like the CLA bot didn't accept the first signature.

2021-07-01 16:08 UTC, balopat commented
As we discussed this on Cirq Cynque, numpy is way too central to Cirq to risk switching it out. For users who want to leverage GPU based speedups, qsim will provide GPU integrations soon. At this point we are not ready to take this risk in Cirq. Thank you for the prototype though, it was a very interesting experiment!

2021-07-01 16:08 UTC, closed without merging