Qasm for pauli X sqrts
quantumlib/Cirq pull request #4113
Opened 2021-05-17 15:54 UTC by stubbi

addresses #3728 

The issue mentions to [check other stabilizer operations like X**-0.5, Y**0.5, Y**-0.5, Z**0.5 too](https://github.com/quantumlib/Cirq/issues/3728#issue-799012988). According to the [qiskit docs](https://qiskit.org/documentation/apidoc/circuit_library.html), there exist only `X**0.5` as `xs` and `X**-0.5` as `xsdg`. Both of these conversions have been implemented and tests are passing.

2021-05-17 16:01 UTC, stubbi commented
@googlebot I fixed it.

2021-05-17 17:44 UTC, stubbi commented
closing for now, got to fix the coverage check

2021-05-17 21:31 UTC, tanujkhattar commented
It looks  [`stabilizer_simulator`](https://github.com/Qiskit/qiskit-aer/blob/df38186962e92494b13cfa88bd26558ba73bc418/qiskit/providers/aer/backends/aer_simulator.py#L341)  supports `sx`, `s`, `sdg` but not `sxdg`. 

1) For `ZPowGate`; `cirq.Z ** 0.5` currently outputs `rz(pi*0.5)`  but should output `s`. Similarly `cirq.Z ** -0.5` should output `sdg`.

2) For `XPowGate`; I'm not sure why their simulator does not support `sxdg`. Maybe @Strilanc  can comment what should be expected behaviour here.

2021-05-17 21:40 UTC, tanujkhattar requested changes
FYI, if we `transpile` a circuit with`sxdg` to the `stabilizer_simulator` backend, it decomposes `sxdg` to `SHS`.  Maybe we should directly output this decomposition for `cirq.X ** -0.5` ? 
```python
In [2]: circ = QuantumCircuit(2)
    ...: circ.sx(0)
    ...: circ.sxdg(1)
    ...: print(circ)
    ...: simulator = Aer.get_backend('aer_simulator_stabilizer')
    ...: circ = transpile(circ, simulator)
    ...: print(circ)
      ┌────┐
q_0: ─┤ √X ├─
     ┌┴────┴┐
q_1: ┤ √XDG ├
     └──────┘
global phase: -π/4
     ┌────┐
q_0: ┤ √X ├──────────
     ├───┬┘┌───┐┌───┐
q_1: ┤ S ├─┤ H ├┤ S ├
     └───┘ └───┘└───┘
```
In the meantime, please make the changes for `cirq.ZPowGate`.

2021-05-18 08:18 UTC, stubbi commented
@tanujkhattar thanks for your review, good catches!

I added the requested changes for the `ZPowGate` and [opened an issue in qiskit-aer](https://github.com/Qiskit/qiskit-aer/issues/1254) to ask if the `sxdg` isn't included on purposes or had been overlooked.

I would propose to revert the changes for `XPowGate(-0.5)` for now and wait for a reply in the qiskit issue to see if we have to change its output to `sxdg` or `s h s`. What do you think?

2021-05-31 19:28 UTC, tanujkhattar commented
Sounds good, Please revert the changes to `sxdg` and update the original issue with the details (let's keep it open so we can track the progress on the qiskit issue).

2021-06-08 08:05 UTC, stubbi commented
@tanujkhattar I reverted the changes for `sxdg` and [left a comment in the issue](https://github.com/quantumlib/Cirq/issues/3728#issuecomment-856544854)

2021-06-18 22:03 UTC, tanujkhattar approved these changes
LGTM

2021-06-18 22:10 UTC, merged