[4173] Add aotl/rotl for unitary checks in matrixGate
quantumlib/Cirq pull request #4220
Opened 2021-06-17 15:35 UTC by shivanth

2021-06-17 15:42 UTC, shivanth commented
@googlebot I signed it!

2021-06-17 16:19 UTC, balopat requested changes
Thank you for adding this! Can you please add unit tests for the new parameters?

2021-06-18 16:49 UTC, balopat commented
Looks good, please run `check/format-incremental --apply`

2021-06-18 16:49 UTC, balopat approved these changes

2021-06-21 23:41 UTC, merged