Added docstyle to pylint, and preformed the suggested refactor.
quantumlib/Cirq pull request #4235
Opened 2021-06-20 18:55 UTC by thanacles

2021-06-20 18:57 UTC, thanacles commented
This is related to Issue: https://github.com/quantumlib/Cirq/issues/3388

add to docstyle to pylint and performed the suggested refactor.

2021-06-22 14:33 UTC, balopat requested changes
Thanks for doing this! I think this is looking promising - one major issue at first blink: can you change the constructors to follow the Google style guide? (I know, we are all over the place regarding to it in the code base). 

Namely, the first line should be always a short description of the method, we should never start with `Args`. In the constructor case the args should be moved to `Attributes` on the class. https://google.github.io/styleguide/pyguide.html#384-classes

I'll keep reviewing.

2021-06-22 14:33 UTC, balopat commented on cirq-aqt/cirq_aqt/aqt_sampler.py
> +        """Args:
First line should be a description of the method. In this case I think the args should be moved to `Attributes` on the class. https://google.github.io/styleguide/pyguide.html#384-classes

2021-06-22 14:33 UTC, balopat commented on cirq-core/cirq/circuits/optimization_pass.py
> +        """Args:
First line should be a description of the method. In this case I think the args should be moved to `Attributes` on the class. https://google.github.io/styleguide/pyguide.html#384-classes

2021-06-22 14:33 UTC, balopat commented on cirq-core/cirq/circuits/optimization_pass.py
> +        """Args:
First line should be a description of the method. In this case I think the args should be moved to `Attributes` on the class. https://google.github.io/styleguide/pyguide.html#384-classes

2021-06-22 14:33 UTC, balopat commented on cirq-core/cirq/contrib/graph_device/graph_device.py
>      ) -> None:
First line should be a description of the method. In this case I think the args should be moved to `Attributes` on the class. https://google.github.io/styleguide/pyguide.html#384-classes

2021-06-22 14:53 UTC, thanacles commented
@balopat That makes sense, for most of the cases.  I'll rename Args -> Attributes and move the comment from the constructor to the class, but it does seem like a few of the constructor args are being assigned to private variables.  I feel we shouldn't mark those as attributes.

2021-06-22 15:00 UTC, thanacles commented
How about this,  I'll update the constructor doc with "Inits ClassName" and leave arguments that get assigned to private variables there.

2021-06-22 15:11 UTC, balopat commented
> How about this, I'll update the constructor doc with "Inits ClassName" and leave arguments that get assigned to private variables there.

I think you're right - `Attributes` should be only used for classes that are just value types, e.g. dataclasses. And it would be a bit of a code smell to have public attributes on classes that define some kind of behavior based on initialization parameters.

Sounds good. Let's keep them separate, add a one liner for the constructors.

2021-06-26 18:11 UTC, thanacles commented
@balopat Done.  What do you think?

2021-06-28 02:53 UTC, closed without merging