Add an option to build a PauliSum from a Sympy Boolean expressions
quantumlib/Cirq pull request #4282
Opened 2021-07-02 21:02 UTC by tonybruguier

As part of the the review #3989 we could use the ability to build a PauliSum from a Boolean expression. This PR makes available that function (smaller change).

2021-07-03 05:31 UTC, tonybruguier commented
@balopat This is one of the smaller PRs you suggested.

2021-07-09 19:34 UTC, balopat requested changes
LGTM with a little nit + it would be nice to add a little explanation in our docs/operators_and_observables.ipynb

2021-07-09 19:34 UTC, balopat commented on cirq-core/cirq/ops/linear_combinations.py
> +        """Builds the Hamiltonian representation of Boolean expression.Builds
```suggestion
        """Builds the Hamiltonian representation of a Boolean expression.
```

2021-07-09 20:10 UTC, balopat commented
Sorry for the linter checks - I am reverting that change.

2021-07-09 20:11 UTC, balopat commented on docs/operators_and_observables.ipynb
> +    "A Pauli sum can also be constructed from a `Sympy` Boolean expression:"
Add in the reference here to the paper.

2021-07-09 20:12 UTC, balopat approved these changes
LGTM with a final nit.

2021-07-09 20:37 UTC, tonybruguier commented
@balopat 
Added the reference to the Jupyter notebook.

2021-07-09 21:22 UTC, merged