Add docstyle rule to the linter and subsequent refactor.
quantumlib/Cirq pull request #4311
Opened 2021-07-10 19:31 UTC by thanacles

2021-07-13 12:57 UTC, balopat requested changes
Awesome! 

I added places where the summary line doesn't follow the style guide (I wish the linter would catch that!): 

https://google.github.io/styleguide/pyguide.html#381-docstrings - "...A docstring should be organized as a summary line (one physical line not exceeding 80 characters) terminated by a period, question mark, or exclamation point..."

2021-07-13 12:57 UTC, balopat commented on examples/qubit_characterizations_example.py
> +    """Examples of how to run various qubit characterizations.  This example
Fix summary.

2021-07-13 12:57 UTC, balopat commented on examples/quantum_fourier_transform.py
> +"""Creates and simulates a circuit for Quantum Fourier Transform(QFT)
fix summary

2021-07-13 12:57 UTC, balopat commented on examples/hhl.py
> +    """Simulates HHL with matrix input, and outputs Pauli observables of the
fix summary

2021-07-13 12:57 UTC, balopat commented on examples/hhl.py
> +    """EigenRotation performs the set of rotation on the ancilla qubit equivalent
fix summary

2021-07-13 12:57 UTC, balopat commented on examples/hhl.py
> +"""Demonstrates the algorithm for solving linear systems by Harrow, Hassidim,
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """Implementation of direct fidelity estimation, as per 'Direct Fidelity
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """A container for the various debug and run data from calling the function
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """Estimates the Pauli traces in case the circuit is not Clifford. In this case
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """Estimates the Pauli traces in case the circuit is Clifford. When we have a
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """A class that contains the Pauli states as described on page 2 of:
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """Given a stabilizer basis, creates the exhaustive list of Pauli states that
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """Given a stabilizer basis, randomly creates Pauli states by including the
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/direct_fidelity_estimation.py
> +    """Estimates the characteristic function using a (noisy) circuit simulator by
fix summary line

2021-07-13 12:57 UTC, balopat commented on examples/bell_inequality.py
> +"""Bell's theorem or inequality proves that entanglement based
fix summary line

2021-07-13 12:57 UTC, balopat commented on dev_tools/incremental_coverage.py
> +    """Uses git diff and the annotation files created by
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-pasqal/cirq_pasqal/pasqal_sampler_test.py
> +    """Encodes a random binary number in the qubits, sweeps between odd and even
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py
> +    """Implement a cphase using the Ising gate generated from 2 Sycamore gates
```suggestion
    """Implements a cphase using the Ising gate generated from 2 Sycamore gates.
```

2021-07-13 12:57 UTC, balopat commented on cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py
> +    """Given two unitaries with the same interaction coefficients but different
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py
> +    """Synthesize a known gate operation to a sycamore operation
```suggestion
    """Synthesizes a known gate operation to a sycamore operation.
```

2021-07-13 12:57 UTC, balopat commented on cirq-google/cirq_google/optimizers/convert_to_sycamore_gates.py
> +        """Decomposer intercept:  Upon cirq.protocols.decompose catch and
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-google/cirq_google/optimizers/convert_to_sqrt_iswap.py
> -        """
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-google/cirq_google/engine/client/quantum_v1alpha1/gapic/enums.py
let's turn off pylint for this full file, I think this is generated.

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/study/resolver_test.py
> +    """Calling cirq.resolve_paramters on a ParamResolver composes that resolver
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/study/resolver_test.py
> +    """Param dicts are allowed to have str or sympy.Symbol as keys and
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/sim/sparse_simulator_test.py
> +    """A previous version of cirq made the mistake of assuming that it was okay to
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/protocols/json_serialization.py
> +    """Create a dataclass that supports JSON serialization
```suggestion
    """Create a dataclass that supports JSON serialization.
```

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/protocols/has_stabilizer_effect_protocol.py
> +    """Returns whether the input has a stabilizer effect.
```suggestion
    """Returns whether the input has a stabilizer effect.
    
```

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/ops/fsim_gate.py
> +        """inits FSimGate.
```suggestion
        """Inits FSimGate.
```

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
> +        """Determines if it's possible to add an operation into a moment. An
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/contrib/acquaintance/strategies/complete.py
> -    Returns an acquaintance strategy capable of executing a gate corresponding
fix summary line

2021-07-13 12:57 UTC, balopat commented on cirq-core/cirq/contrib/acquaintance/mutation_utils.py
> +    """Replace every moment containing acquaintance gates (after
fix summary line

2021-07-13 14:37 UTC, thanacles commented
Thanks @balopat .  Since this is such a big change, I'm trying to keep all my changes trivial.  For the non-trivial cases, what do you think about me adding a TODO to update the docstring with a summary line?

2021-07-13 15:45 UTC, balopat commented
> Thanks @balopat . Since this is such a big change, I'm trying to keep all my changes trivial. For the non-trivial cases, what do you think about me adding a TODO to update the docstring with a summary line?

Sounds good to me. A TODO + disabling pylint is better than a bad update.

2021-07-13 17:19 UTC, thanacles commented on cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
> +        """Raises an error if the provided gate isn't part of the native gate set.
I'd argue that this is a good summary line for this validate method.  It's concern is to raise an error if it fails validation.  Also it has a Raises section below.

2021-07-13 17:19 UTC, thanacles commented on cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
> +        """Raises an error if the given operation is invalid on this device.
Same as above.

2021-07-13 17:19 UTC, thanacles commented on cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
> +        """Raises an error if the given moment is invalid on this device
ditto

2021-07-13 17:22 UTC, thanacles commented on cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
> +        """Raises an error if the given moment is invalid on this device
ditto

2021-07-13 19:57 UTC, thanacles commented
@balopat Thanks again for bearing with me.  I think this lint rule will be nice once it's running implemented.  I've taken care of your suggestions, take a look.

2021-07-14 15:41 UTC, balopat commented on cirq-core/cirq/neutral_atoms/neutral_atom_devices.py
> +        """Raises an error if the given operation is invalid on this device.
sounds good!

2021-07-14 15:42 UTC, balopat approved these changes
LGTM

2021-07-14 16:03 UTC, merged