Make sure (cirq.X, cirq.Y, cirq.Z)**1 should be _Pauli{X,Y,Z} instead of {X,Y,Z}PowGate
quantumlib/Cirq pull request #4330
Opened 2021-07-17 04:48 UTC by ybc1991

Fix #4328

2021-07-19 21:34 UTC, MichaelBroughton requested changes
In the `__pow__` method there is a contract to return an instance of `XPowGate`. When returning `self`, you return a **reference** to an `XPowGate` and not a new object. That means with your code I could do:

```python3
assert cirq.X.global_shift == 0.0
a = [cirq.X**1.0, cirq.X**3.0]
a[0]._global_shift = 1.0
assert cirq.X.global_shift == 1.0
```
Which isn't great. I think modifying the code so that you are returning new instances in both cases would fix this.

2021-07-19 21:34 UTC, MichaelBroughton commented on cirq-core/cirq/ops/pauli_gates.py
> +        return common_gates.XPowGate(exponent=exponent) if exponent != 1 else self
`self` -> `_PauliX()`

2021-07-19 21:34 UTC, MichaelBroughton commented on cirq-core/cirq/ops/pauli_gates.py
> +        return common_gates.YPowGate(exponent=exponent) if exponent != 1 else self
`self` -> `_PauliY()`

2021-07-19 21:34 UTC, MichaelBroughton commented on cirq-core/cirq/ops/pauli_gates.py
> +        return common_gates.ZPowGate(exponent=exponent) if exponent != 1 else self
`self` -> `_PauliZ()`

2021-07-20 04:17 UTC, ybc1991 commented on cirq-core/cirq/ops/pauli_gates.py
> +        return common_gates.XPowGate(exponent=exponent) if exponent != 1 else self
Done

2021-07-20 04:17 UTC, ybc1991 commented on cirq-core/cirq/ops/pauli_gates.py
> +        return common_gates.YPowGate(exponent=exponent) if exponent != 1 else self
Done

2021-07-20 04:17 UTC, ybc1991 commented on cirq-core/cirq/ops/pauli_gates.py
> +        return common_gates.ZPowGate(exponent=exponent) if exponent != 1 else self
Done.

2021-07-20 04:19 UTC, ybc1991 commented
> In the `__pow__` method there is a contract to return an instance of `XPowGate`. When returning `self`, you return a **reference** to an `XPowGate` and not a new object. That means with your code I could do:
> 
> ```python
> assert cirq.X.global_shift == 0.0
> a = [cirq.X**1.0, cirq.X**3.0]
> a[0]._global_shift = 1.0
> assert cirq.X.global_shift == 1.0
> assert a[1].global_shift == 0.0
> ```
> 
> Which isn't great. I think modifying the code so that you are returning new instances in both cases would fix this.

Yeah, that is a good point. Totally agreed that ___pow__ should return a new instance.

2021-07-20 16:14 UTC, MichaelBroughton approved these changes
LGTM

2021-07-20 16:36 UTC, merged