Define cirq.ISWAP_INV
quantumlib/Cirq pull request #4624
Opened 2021-11-03 19:53 UTC by unaiic

Define a global constant for `cirq.ISWAP_INV`, similar to `cirq.SQRT_ISWAP_INV`, and replace usages of `cirq.ISWAP ** -1` with `cirq.ISWAP_INV`.

Fixes #4615.

2021-11-07 18:23 UTC, dabacon approved these changes

2021-11-07 18:23 UTC, dabacon commented on cirq-google/cirq_google/serialization/common_serializers_test.py
> +        (cirq.ISWAP_INV, np.pi / 2, 0),
nit: move down below other ISWAP.   Also considering adding another case like cirq.ISWAP_INV ** 0.5

2021-11-08 21:08 UTC, tanujkhattar requested changes
Please create `cirq-core/cirq/protocols/json_test_data/ISWAP_INV.json` and `cirq-core/cirq/protocols/json_test_data/ISWAP_INV.repr` to fix the tests. You can look at existing json and repr files for `ISWAP` for reference.  

Please also add tests to cirq-core/cirq/ops/swap_gates_test.py by extending the existing tests for `cirq.SWAP`.

2021-12-01 18:39 UTC, tanujkhattar commented
@unaiic Gentle reminder. Please address the comments and fix the failing tests so that we can merge the PR.

2022-06-25 00:17 UTC, dabacon commented
Implemented in #5613

2022-06-25 00:17 UTC, closed without merging