Rename (qubits+cbits) to labels
quantumlib/Cirq pull request #4675
Opened 2021-11-12 19:10 UTC by daxfohl

Follow-up to #4627 that renames diagram lines from "qubits" to "labels", since they now contain control keys as well. (Do not review until #4627 is merged)

2021-11-20 16:12 UTC, daxfohl commented
@95-martin-orion ping this should be quick

2021-11-22 15:43 UTC, 95-martin-orion requested changes
Doesn't look like there are any public API changes. Couple of type-annotation requests, but otherwise this is ready.

2021-11-22 15:43 UTC, 95-martin-orion commented on cirq-core/cirq/protocols/circuit_diagram_info_protocol.py
> +        label_map: The map from label entities to diagram positions.
I think it's worth defining "label entity" here (IIUC, it's a `Qid` or a `MeasurementKey`).

2021-11-22 15:43 UTC, 95-martin-orion commented on cirq-core/cirq/circuits/circuit.py
> +        cbits: Tuple[Any, ...] = tuple(
Is it possible for `qubits` and `cbits` to have types `Tuple[Qid, ...]` and `Tuple[MeasurementKey, ...]`, respectively? Similarly, can `labels` have type `Tuple[Union[Qid, MeasurementKey], ...]`?

2021-11-22 19:40 UTC, 95-martin-orion approved these changes

2021-11-22 19:59 UTC, merged