Add runtime estimator
quantumlib/Cirq pull request #4718
Opened 2021-12-01 17:43 UTC by dstrain115

- Adds a utility to estimate runtime for QCS
- Estimates single circuit runs, sweeps, and batches.
- This is a rough approximation and only accurate to about 25% or so.

2021-12-01 18:41 UTC, 95-martin-orion requested changes
This is really impressive! In my experience fiddling with these numbers, consistently estimating within 50% of the target was a challenge, much less 25%.

The one thing I think is missing from this PR is documentation on how to reproduce these values for future devices. Happy to discuss this offline if it's not something we're ready to make public.

2021-12-02 17:43 UTC, dstrain115 commented
Added a line about how the rep rate calculator was used to get timings and that the model was fitted by hand.
Also added to the engine init file.

2021-12-02 18:41 UTC, MichaelBroughton reviewed
High level question:

Given your description of how tightly these estimates match reality (25%); how you drew the data by hand to fit the model (I'm guessing the numbers present in the test); and how all the functions seem to be based around a few basic variables `width`, `depth`, `n_qubits` etc.

What do we think about just turning this into a purely statistical set of functions ?
1. Fit a linear model on these variables.
2. Write out the functions to just be:
```python3
def run_sweep_time(circuit, ... ,...):
  _run_swee_internal(depth, weidth, etc.)

def _run_sweep_internal(x, y, z):
  return 0.3 * x + 2.9 * y - 4.8 * z
```
This seems like a process that might be a little more robust to internal changes (all we have to do is re-fit the coefficients and we've updated it to the latest behavior vs. having to rewrite more complicated code to bake in assumptions from the changed underlying process). What do you think ?

2021-12-02 18:50 UTC, 95-martin-orion reviewed
My comments have been addressed - leaving to @MichaelBroughton for final approval.

2021-12-03 01:19 UTC, dstrain115 commented on cirq-google/cirq_google/engine/runtime_estimator_test.py
> +        (2, 2560, 16000, 16, 38.9),
Yes.

2021-12-03 02:11 UTC, dstrain115 commented
> This seems like a process that might be a little more robust to internal changes (all we have to do is re-fit the coefficients and we've updated it to the latest behavior vs. having to rewrite more complicated code to bake in assumptions from the changed underlying process). What do you think ?

We could try to fit a linear model.  I think there are some step functions in here that might not be captured well that I managed to work around in my hand-fitting.  I think the function I wrote though is mostly linear though, so I can give it a try.

2021-12-06 21:13 UTC, MichaelBroughton approved these changes
LGTM

2021-12-06 21:15 UTC, dstrain115 commented
Update: linear model did not fit very well.  It is at least twice as bad as the hand-tuned model that I used.  It also has a intercept which marks many data points as negative amounts of time, which is not ideal.  Though it will be much harder to update this hand-tuned model, I recommend sticking with it for now until an (as yet unforeseen) need for frequent updating causes us to reevaluate this approach.

2021-12-06 22:26 UTC, merged