Deprecate qid pairs
quantumlib/Cirq pull request #4900
Opened 2022-01-27 00:07 UTC by MichaelBroughton

Deprecate `qid_pairs`. Next step on #4744 .

This also makes a small update to the DeviceMetadata to remove make optional fields required (since the metadata property itself is optional this seems fine).

2022-01-27 19:07 UTC, 95-martin-orion requested changes
Looks clean overall, just a couple refactoring requests.

2022-01-27 20:10 UTC, MichaelBroughton commented on cirq-core/cirq/contrib/graph_device/graph_device.py
> +def _block_overlapping_deprecation():
Opened #4904

2022-01-27 20:58 UTC, MichaelBroughton commented on cirq-core/cirq/contrib/graph_device/graph_device.py
> +        fix='qubit coupling data can now be found in device.metadata if provided.',
Updated.

2022-01-28 18:03 UTC, 95-martin-orion approved these changes

2022-01-28 19:23 UTC, merged