Allow partial state vector function to handle qudits
quantumlib/Cirq pull request #5077
Opened 2022-03-14 17:47 UTC by daxfohl

Add handling for qudits within `partial_trace_of_state_vector_as_mixture`

Fixes #3003

2022-03-14 20:42 UTC, 95-martin-orion requested changes
Couple of nits. I like the new tests - the random one is a strong indicator that this behaves as expected, and the pair-of-qutrits illustrates partial-trace behavior nicely.

2022-03-14 20:42 UTC, 95-martin-orion commented on cirq-core/cirq/linalg/transformations.py
> +            raise EntangledStateError('The tensor cannot be factored by the requested axes')
This is covered by the partial trace fallback tests, but we really should have an isolated test of the `EntangledStateError` path for `factor_state_vector`.

2022-03-15 20:13 UTC, 95-martin-orion approved these changes

2022-03-15 20:36 UTC, daxfohl commented
Oh, cirqbot...

2022-03-15 20:48 UTC, merged