Fix Docs: cirq/tutorials/educators/chemistry
quantumlib/Cirq pull request #5251
Opened 2022-04-12 12:53 UTC by TimoEckstein

This fixed the broken Latex formulas in https://quantumai.google/cirq/tutorials/educators/chemistry, which are not broken on Github or Colabs. 

It is fixed by putting the broken Latex formulas into one line, like the not broken ones. 

xref https://github.com/quantumlib/Cirq/issues/5151

2022-04-12 14:38 UTC, dabacon requested changes
Think you dropped a "+" sign in one of the formulas, but otherwise looks great!

Also it looks like you'll need to sign the CLA.  If you have questions about the CLA, feel free to ask them in this conversation.

2022-04-12 14:38 UTC, dabacon commented on docs/tutorials/educators/chemistry.ipynb
> +    "\\sum_{p, q} M_{pq} a^\\dagger_p a_q \\frac12 \\sum_{p, q} (\\Delta_{pq} a^\\dagger_p a^\\dagger_q + \\text{h.c.})\n",
I think this lost a "+"?

2022-04-12 18:33 UTC, TimoEckstein commented
Regarding the CLA: I filled it. 
I guess the initial issue was that the email used on GitHub was not added to my google account. Now, I added my Github-E-Mail to Google and my Google Account E-Mail to Github, respectively.  
![Eckstein_CLA](https://user-images.githubusercontent.com/69790705/163029812-e4fcad9b-b9e5-480b-832b-a561ca0f0938.jpg)

2022-04-14 16:58 UTC, dabacon approved these changes

2022-04-16 15:06 UTC, merged