Remove alpha notice.
quantumlib/Cirq pull request #5811
Opened 2022-07-27 18:23 UTC by MichaelBroughton

2022-07-27 18:27 UTC, maffoo approved these changes

2022-07-27 21:54 UTC, pavoljuhas commented
There seem to be few more alpha disclaimers - can you please fix those as well?

- https://github.com/quantumlib/Cirq/blob/94f9594f82df0169d7f9596f4024c5047ee21a88/release.md?plain=1#L3
- https://github.com/quantumlib/Cirq/blob/94f9594f82df0169d7f9596f4024c5047ee21a88/docs/start/install.md?plain=1#L13
- https://github.com/quantumlib/Cirq/blob/94f9594f82df0169d7f9596f4024c5047ee21a88/docs/start/intro.ipynb?short_path=f5017ef#L145

2022-07-27 21:56 UTC, pavoljuhas requested changes
few more alphas - please see https://github.com/quantumlib/Cirq/pull/5811#issuecomment-1197410237

2022-07-29 23:53 UTC, pavoljuhas approved these changes
LGTM

2022-07-30 00:15 UTC, merged