Adds unitary testing for routed circuits
quantumlib/Cirq pull request #5846
Opened 2022-08-30 22:58 UTC by ammareltigani

Adds utilitiy functions that tests whether two circuits define the same unitary up to permutation of qubits.

2022-08-31 20:39 UTC, tanujkhattar requested changes
As discussed offline, let's change the API of the testing method (and router implementation) to take an `actual` and `expected` circuit with the same set of qubits, along with a `qubit_map` that maps the initial qubits of `actual` to it's final qubit mapping. As a fallback, if the `qubit_map` is not specified, the method can potentially try to construct a qubit map by looking at the swaps operations in the `actual` circuit.

2022-08-31 21:52 UTC, ammareltigani commented
@tanujkhattar I've made the changes we discussed without the fallback strategy as a v1. I can follow up with that with another PR once we have a fully functioning basic routing implementation pushed to Cirq.

2022-09-02 00:48 UTC, tanujkhattar requested changes

2022-09-02 01:08 UTC, tanujkhattar requested changes

2022-09-02 01:08 UTC, tanujkhattar commented on cirq-core/cirq/testing/circuit_compare.py
> +    actual: circuits.Circuit, expected: circuits.Circuit, qubit_map: Dict[ops.Qid, ops.Qid]
```suggestion
    actual: cirq.AbstractCircuit, expected: cirq.AbstractCircuit, qubit_map: Dict[ops.Qid, ops.Qid]
```

2022-09-02 01:08 UTC, tanujkhattar commented on cirq-core/cirq/testing/circuit_compare.py
> +    actual.append(ops.QubitPermutationGate(list(inverse_permutation)).on(*sorted_qubits))
We cannot modify the input circuit. mypy should also start complaining once you change the circuit type to `AbstractCircuit`

2022-09-02 17:44 UTC, tanujkhattar approved these changes

2022-09-02 21:35 UTC, merged