Print multi-qubit circuit with asymmetric depolarizing noise correctly
quantumlib/Cirq pull request #5931
Opened 2022-10-26 20:12 UTC by paaige

Closes #5927

2022-10-27 22:20 UTC, vtomole submitted a review, later dismissed
Congrats on your first pull request to Cirq @paaige!

You'll need to change the return type of the method you modified to make mypy happy followed by signing the CLA in order for us to merge this.

2022-10-31 20:03 UTC, tanujkhattar commented
@paaige This is great. Please also update the `_approx_eq_` method to fix another (unrelated) bug in the same class; as highlighted in the second part of my comment here: https://github.com/quantumlib/Cirq/issues/5927#issuecomment-1291082263

2022-12-19 18:05 UTC, tanujkhattar requested changes
LGTM % nit.

2022-12-19 18:05 UTC, tanujkhattar commented on cirq-core/cirq/ops/common_channels.py
The implementation can be simplified by doing approximate comparison on error_probabilites dictionary directly:
```suggestion
        self_keys, self_values = zip(*sorted(self.error_probabilities.items()))
        other_keys, other_values = zip(*sorted(other.error_probabilities.items()))
        return self_keys == other_keys and protocols.approx_eq(self_values, other_values, atol=atol)
```

2022-12-19 19:55 UTC, tanujkhattar approved these changes
I made the minor changes so we can merge the PR. Thanks for the contribution!

2022-12-19 20:07 UTC, merged