Codecov coverage reports
quantumlib/Cirq pull request #6193
Opened 2023-07-11 16:35 UTC by jackreeceejini

Testing Codecov coverage reports on a PR as per https://github.com/quantumlib/Cirq/issues/6063#issue-1667122621

2023-07-13 19:05 UTC, pavoljuhas commented
Please rebase so this PR contains only codecov-related commits on top of the quantumlib/Cirq master.
As it is the PR has intermediate commits from your previous contribution.

One way of doing the rebase is
```
$ git checkout codecov-coverage-reports
$ git fetch https://github.com/quantumlib/Cirq.git master
$ git rebase -i FETCH_HEAD
  ... keep only the new commits
$ git push --force-with-lease your_remote_name codecov-coverage-reports
```

2023-07-13 23:01 UTC, jackreeceejini commented
I will, thank you very much. I'm learning a lot!

2023-07-21 20:34 UTC, pavoljuhas commented on .github/workflows/ci.yml
> +          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
I think we can take this out, the token is not needed for public repositories - https://github.com/codecov/codecov-action#usage.

2023-07-21 20:40 UTC, pavoljuhas requested changes
@dstrain115 has installed the Codecov App and we got our first coverage report out at
https://app.codecov.io/github/quantumlib/Cirq/commit/1fd59723ba339b9281d150d31825c3791e4f0fdc/tree :tada:

LGTM after removing the unused token settings.

2023-07-25 01:00 UTC, pavoljuhas approved these changes
Thanks!

2023-07-25 01:07 UTC, merged