equivalent measurements evaluate as equal now
quantumlib/Cirq pull request #6234
Opened 2023-08-08 01:05 UTC by Gmontes01

This should solve the issue displayed in problem #6093. It sets the default value of any inversion mask which does nothing to '()'

2023-08-18 19:56 UTC, tanujkhattar requested changes
[Gmontes01](https://github.com/Gmontes01) - Thanks for opening the PR! I think the right thing to do here, as described in the original issue, is to use `self.full_invert_mask()` in `MeasurementGate._value_equality_values_` method and add a corresponding test to make sure new and existing tests pass.

2024-06-07 23:51 UTC, simulified commented
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

2025-01-14 13:31 UTC, dstrain115 commented
This is a stale PR and has been unworked on for over a year.  Please let us know if you are still planning to work on it.  Otherwise, we will close this.

2025-01-15 17:35 UTC, dstrain115 commented
This has been obsoleted by PR #6952

2025-01-15 17:35 UTC, closed without merging