Add registry sweep documentation to cirq_google
quantumlib/Cirq pull request #6291
Opened 2023-09-18 16:19 UTC by dstrain115

- Add some simple documentation on how to use registry sweeps to cirq_google's device page (currently public but not linked to from table of contents)

2023-09-18 18:18 UTC, pavoljuhas commented on docs/google/devices.md
> +a path from the device config's folder (or the "sample folder").`
```suggestion
a path from the device config's folder (or the "sample folder").
```

2023-09-18 18:22 UTC, pavoljuhas commented on docs/google/devices.md
> +sweep = cirq.Linspace("q4_8.piAmp", 0,1,51, metadata = descriptor)
maybe use standard Python formatting here?
```suggestion
sweep = cirq.Linspace("q4_8.piAmp", 0, 1, 51, metadata=descriptor)
```

2023-09-18 18:59 UTC, pavoljuhas requested changes
LGTM, but we can fix a few typos in the document, please see the attached patch.
[typos-in-google-devices.md.patch.txt](https://github.com/quantumlib/Cirq/files/12652299/typos-in-google-devices.md.patch.txt)

2023-09-19 18:44 UTC, dstrain115 commented
@pavoljuhas Is there some issue with your CLA or github registration?  It's having a problem since I committed your suggestions.

2023-09-20 00:44 UTC, pavoljuhas commented
> @pavoljuhas Is there some issue with your CLA or github registration? It's having a problem since I committed your suggestions.

AFAICT, I should be all configured for the CLA check.  The problem seems in commits 1a76baf9183c6a2fda8e467c2fa28dab522af862, ee440ab238ca42018fca2889500cb5ea7c413548 which have `Co-authored-by: ...` note in the commit message.  I have requested CLA override which seems to clear the check here.

2023-09-20 04:42 UTC, pavoljuhas approved these changes

2023-09-20 04:44 UTC, merged