Equivalent Measurements with equivalent invert masks should evaluate …
quantumlib/Cirq pull request #6339
Opened 2023-11-08 18:02 UTC by nishitkshah

…equal

Fix for the issue https://github.com/quantumlib/Cirq/issues/6093 (equivalent measurements evaluate as unequal)

2023-11-13 09:53 UTC, nnnnnnsssss requested changes
Recheck

2024-01-02 18:15 UTC, NoureldinYosri requested changes

2024-01-02 18:15 UTC, NoureldinYosri commented on cirq-core/cirq/ops/measurement_gate.py
> +                return invert_mask
this assumes that `invert_mask` can be `None` which it's not
https://github.com/quantumlib/Cirq/blob/d33b1a71ac9721e762a2fa1b9e9871edfe187a3c/cirq-core/cirq/ops/measurement_gate.py#L52

2024-01-02 18:15 UTC, NoureldinYosri commented on cirq-core/cirq/ops/measurement_gate.py
> +        def right_trim_mask(invert_mask):
add type hint
```py3
def right_trim_mask(invert_mask: Tuple[bool, ...]) -> Tuple[bool, ...]:
```

2024-08-15 00:24 UTC, closed without merging