Create a workflow to perform FSim based z-phase calibration
quantumlib/Cirq pull request #6568
Opened 2024-04-22 20:14 UTC by NoureldinYosri

2024-04-24 16:46 UTC, eliottrosenberg requested changes
This is a great start, Nour!! Thanks for all of your amazing work.

2024-04-24 19:24 UTC, eliottrosenberg commented
This should probably go in a separate PR, but I think the next step after this is to write a transformer that replaces the two-qubit gates in a circuit with ones that correct for these z-phases.

2024-04-30 22:08 UTC, NoureldinYosri commented on cirq-core/cirq/experiments/z_phase_calibration.py
> +            using the representation of a two-qubit gate as an FSimGate for the initial guess.
fixed, it should work now

2024-04-30 22:16 UTC, NoureldinYosri commented on cirq-core/cirq/experiments/z_phase_calibration.py
> +            using the representation of a two-qubit gate as an FSimGate for the initial guess.
btw to speed things up, run the calibration method in a multiprocessing pool e.g.
```py3
with mulitprocessing.Pool(10) as pool:
    result_zphase = cirq.experiments.calibrate_z_phases(sampler, qubits, pool=pool)
```

2024-05-06 21:46 UTC, eliottrosenberg commented on cirq-core/cirq/experiments/z_phase_calibration.py
> +            using the representation of a two-qubit gate as an FSimGate for the initial guess.
Could we make it create a pool by default?

2024-12-20 00:55 UTC, NoureldinYosri commented
@mhucka  I already implemented this in a different PR

2024-12-20 00:55 UTC, closed without merging

2024-12-20 01:00 UTC, mhucka commented
Ah, it looked like it was closed by the bot due to being stale.

Is the PR #6657?

2024-12-20 01:03 UTC, mhucka commented
Then, could you please list the other ones, so that there's a trail for future maintainers?