Add first draft of ZXTransformer to contrib.
quantumlib/Cirq pull request #6647
Opened 2024-06-13 18:45 UTC by dlyongemallo

This is a custom transformer which uses ZX-calculus through the PyZX library to perform circuit optimisation.

See issue #6585.

2024-06-24 21:05 UTC, NoureldinYosri requested changes

2024-06-24 21:05 UTC, NoureldinYosri commented on cirq-core/cirq/contrib/zxtransformer/zxtransformer.py
> +        self.qubits: List[cirq.Qid] = []
I don't think the qubits and qubit_to_index map should be properities of the class. they are properties of the circuit being transformed so they shouldn't be stored this way. 

Actually I don't think this transfomer need to be class. I think it should be a function
```py3
@transformer
def zx_transfomer(circuit: circuits.AbstractCircuit, context: Optional[cirq.TransformerContext] = None, optimizer: Callable[[zx.Circuit], zx.Circuit] = _optimize) -> circuits.AbstractCircuit
```
The qubits and qubit_to_index lists should be passed as arguments to the methods that need them.

2024-07-09 09:12 UTC, dlyongemallo commented on cirq-core/cirq/contrib/zxtransformer/zxtransformer.py
> +        return zx_gates.XPhase(*qubits, phase=cirq_gate.exponent)  # type: ignore
`Expected type 'Fraction | int | Poly', got 'Float | Expr' instead.`

2024-07-09 17:58 UTC, NoureldinYosri commented on cirq-core/cirq/contrib/zxtransformer/zxtransformer.py
> +        return zx_gates.XPhase(*qubits, phase=cirq_gate.exponent)  # type: ignore
I think this should fix it, cirq gates support symbolic properties but pyzx doesn't.

```suggestion
        return zx_gates.XPhase(*qubits, phase=float(cirq_gate.exponent)) 
```

alternatively you can inspect the type of the exponent and raise an error if it's a sympy expr

2024-09-29 00:31 UTC, closed without merging

2024-12-20 01:03 UTC, NoureldinYosri commented
@mhucka the contributer has indicated in the issue that they don't have time to work on this https://github.com/quantumlib/Cirq/issues/6585#issuecomment-2382014994

2024-12-20 01:10 UTC, mhucka commented
That's correct, but they asked if someone else could take it over; they didn't say to close it. Moreover, the associated issue is still open. Since this PR was auto-closed by bot due to staleness, it seems like the right action is to reopen it and at least have a discussion about whether both the issue and the PR should be closed deliberately.

2025-01-14 13:54 UTC, dstrain115 commented
@naerabati Are you still interested in doing work on the ZX calculus transformer?  Want to pick this up?

2025-01-17 15:04 UTC, naerabati commented
Sorry I couldn't answer earlier! I don't think right now I will have the time to finish the transformer either

2025-01-17 15:11 UTC, naerabati commented
@dstrain115 @dlyongemallo would you be able to tell me what else needs to implemented to complete this PR?

2026-04-02 01:12 UTC, mhucka commented
Closing due to inactivity.

2026-04-09 12:27 UTC, dlyongemallo commented
I can actually pick this back up. I recently updated the change to use `pyzx` 0.10.0, which adds support for `reset` and `measurement` operations which were previously not available when this PR was first created.

What needs to be done from my end to get this merged?

2026-04-09 15:47 UTC, mhucka commented
@dlyongemallo Thank you for your work. It looks like GitHub will not let me reopen this PR; I get an error message that the branch was "either force-pushed or recreated".

It's possible GitHub will let you reopen it. If the button to reopen the PR is available to you, go ahead and click it.

If it is not available, then the easiest thing to do would be to open a fresh PR. In the PR description, you can write something to the effect of "continuation of PR #6647" or something like that, to help people follow.

2026-04-10 08:06 UTC, dlyongemallo commented
@mhucka I wasn't able to re-open this. I've opened a fresh PR #8026.