Speed up `MutablePauliString.inplace_after`
quantumlib/Cirq pull request #6702
Opened 2024-08-16 22:29 UTC by perlinm

I wrote a custom stabilizer-like simulator in Cirq for [this paper](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.108.062426) ([arXiv](https://arxiv.org/abs/2007.09804)), which involved commuting Pauli strings through circuit operations.  The speed of my simulations turned out to be limited by calls to `protocols.commutes` inside `MutablePauliString.inplace_after`.  I found that checking conditions for commutation "manually" led to considerable speedups, and figured I could push this change upstream.

As an example, on my laptop the changes in this PR reduce the runtime of the script below from ~2 minutes to ~39 seconds.

```python
#!/usr/bin/env python3
import random

import cirq

circuit = cirq.testing.random_circuit(
    qubits=cirq.LineQubit.range(10),
    n_moments=100,
    op_density=0.5,
    gate_domain={cirq.Z: 1, cirq.H: 1, cirq.S: 1, cirq.CX: 2, cirq.CZ: 2},
    random_state=0,
)

for seed in range(10**4):
    random.seed(seed)
    pauli_ops = {
        qubit: random.choice([cirq.I, cirq.X, cirq.Y, cirq.Z])
        for qubit in circuit.all_qubits()
    }
    string = cirq.PauliString(pauli_ops).mutable_copy()
    string.inplace_after(circuit)
```

2024-08-16 22:37 UTC, perlinm commented
It occurs to me that there are other places in the changed file that check for commutation of two Pauli operators.  Perhaps I should just add a `_pauli_commutes` method to the file, and use that everywhere within?

2024-08-16 22:59 UTC, vtomole requested changes
It's better to move this optimization to the [commutes_protocol](https://github.com/quantumlib/Cirq/blob/8d8a6c57fd5c0117026357d4b3ad8662f787235c/cirq-core/cirq/protocols/commutes_protocol.py#L86) in a section that checks if the inputs are Pauli and leave these files as-is.  That way any time `protocols.commute` is called this optimization can be applied if the inputs are paulis.

2024-08-16 23:24 UTC, perlinm commented
If I work with the commutes protocol, it looks like one neat option is to add something like
```python
    def _commutes_(self, other: Any, *, atol: float = 1e-8) -> bool:
        return True
```
to [`cirq.ops.identity.IdentityGate`](https://github.com/quantumlib/Cirq/blob/8d8a6c57fd5c0117026357d4b3ad8662f787235c/cirq-core/cirq/ops/identity.py#L30).  That results in a nearly identical speedup of 2 min --> 40 sec in my original example.

This change seems reasonable because the identity gate should commute with anything, but I'm not sure whether `IdentityGate._commutes_` should return `NotImplemented` for certain "invalid" types of `other`.  Thoughts?

2024-08-16 23:49 UTC, vtomole commented
What sorts of  "invalid" types come to mind?

2024-08-16 23:59 UTC, perlinm commented
None come to mind for me 🙂

If you think that addition to IdentityGate is good, I'll just go ahead and add it.

2024-08-17 00:06 UTC, vtomole commented
The change to `IdentityGate` sounds good to me.

2024-08-17 00:15 UTC, pavoljuhas commented
> This change seems reasonable because an identity gate commutes with everything, but I'm not sure whether `IdentityGate._commutes_` should return `NotImplemented` for certain "invalid" types of `other`. Thoughts?

Using the IdentityGate option sounds great.  The current `IdentityGate._commutes_` inherits from the `Gate`
which returns NotImplemented for non-gate arguments.  I think we should keep that behavior, because it can expose bugs in the calling code.

We don't need to reproduce the `qid_shape` check (line 477), because IdentityGate behaves as a plain wire which commutes.

https://github.com/quantumlib/Cirq/blob/8d8a6c57fd5c0117026357d4b3ad8662f787235c/cirq-core/cirq/ops/raw_types.py#L472-L481

2024-08-17 00:24 UTC, pavoljuhas requested changes
The IdentityGate variant sounds great, thanks!

2024-08-17 04:13 UTC, perlinm commented
@pavoljuhas great!  I think this is the sort of thing I was potentially worried about with invalid inputs.  How are the current changes?  I'm not exactly sure what kind of test makes sense for `IdentityGate._commutes_`...

2024-08-18 06:20 UTC, pavoljuhas commented on cirq-core/cirq/ops/identity_test.py
> +    assert cirq.I._commutes_("placeholder") is NotImplemented
It is better to check this works as intended in the API function -

```suggestion
    assert cirq.commutes(cirq.I, cirq.X)
    with pytest.raises(TypeError):
        cirq.commutes(cirq.I, "Gate")
```

2024-08-18 06:22 UTC, pavoljuhas requested changes
One small suggestion, otherwise LGTM.

2024-08-18 18:50 UTC, vtomole reviewed
Why revert `cirq.commutes(cirq.I, cirq.X)`?

2024-08-18 18:56 UTC, perlinm commented
My thinking was to ensure that this test calls `IdentityGate._commutes_`, rather than deciding that `cirq.I` commutes with `cirq.X` for independent reasons.

2024-08-18 19:36 UTC, vtomole commented
> change it back though if you prefer.

Let's do that. We try to write tests the way an external user would call the API.

2024-08-18 19:45 UTC, perlinm commented
Makes sense.  Done.

2024-08-18 22:05 UTC, vtomole approved these changes
LGTM!

2024-08-19 03:28 UTC, merged