Fixed issue #6717
quantumlib/Cirq pull request #6722
Opened 2024-09-08 05:30 UTC by ashiq-firoz

I have updated **mypy.ini** inside **dev_tools** and also made modifications in all **__init__.py** files to match 
```
from foo import bar as bar
```

2024-09-09 17:10 UTC, pavoljuhas requested changes
Please, also update the `cirq-core/cirq/__init__.py` and remove any wip code such as `from foo import bar`.

Make sure the CI-reported errors are all addressed.  You may want to setup a local development environment following https://github.com/quantumlib/Cirq/blob/main/docs/dev/development.md#setting-up-an-environment.

After that you can use `check/mypy`, `check/pylint` to run the respective CI tests locally.
Running `check/format-incremental --apply` would fix code formatting of any changed files.

Thank you for taking this on!

2024-09-09 17:11 UTC, ashiq-firoz commented on cirq-core/cirq/experiments/__init__.py
> +from foo import bar as bar
Sure I will work on that

2024-09-10 16:40 UTC, ashiq-firoz commented
I have made a push now, please review the pull request @pavoljuhas

2024-09-11 22:35 UTC, pavoljuhas commented
@ashiq-firoz - I have updated your PR so that the `no_implicit_reexport` mypy rule is checked only for the cirq modules and not for imported dependencies.  I have also cleaned up unnecessary re-exports of sub-modules, which are automatically added to their parent namespace.  PTAL and let me know if you have comments / suggestions.

If this passes the CI, I feel it should be good to go.

2024-09-11 23:20 UTC, mhucka approved these changes
LGTM.

2024-09-11 23:49 UTC, pavoljuhas approved these changes

2024-09-11 23:49 UTC, merged