Update and refresh cirq-* module README files
quantumlib/Cirq pull request #6900
Opened 2024-12-31 00:07 UTC by mhucka

This updates all the cirq-* module files to fix some broken image links, spiff up the layout and formatting, and add some additional links here and there.

As before, these remain purposefully short and fairly minimal because these are add-only modules to the main `cirq` distribution. The main package README will be much fuller.

Due to differences in reStructuredText support between GitHub and PyPI, some desirable attractive formatting cannot be achieved without using raw HTML, which PyPI does not support. I decided to focus on PyPI rather than GitHub for these README files; the rationale is that these modules are separate packages on PyPI and thus have their own landing pages there, which makes them more visible than on GitHub where they are buried in subdirectories of the overall Cirq repo. Consequently, these files look slightly better on PyPI than on GitHub.

Here are a couple of examples of what the result looks like on PyPI:

<div align="center">
<img width="80%" alt="image" src="https://github.com/user-attachments/assets/71a3d42c-9426-4620-aadd-b9b412524583" />

<img width="80%" alt="image" src="https://github.com/user-attachments/assets/99f6669e-921e-41f2-8eaf-e734b3b8c68d" />
</div>

2025-01-14 03:19 UTC, dstrain115 commented on cirq-google/README.rst
> +<https://quantumai.google/cirq/google/concepts>`__. It also contains
Should we clarify here (and maybe in the other vendor packages) that this is only open to authorized partners?  (i.e. it's not _everything_ you need)

2025-01-14 16:36 UTC, mhucka commented on cirq-google/README.rst
> +<https://quantumai.google/cirq/google/concepts>`__. It also contains
What do you think of the revised version? 

There was a boxed paragraph two paragraphs below the paragraph where the text above appears; I moved that box right under the first paragraph so that the note is more obvious. Please let me know what you think.

2025-01-15 21:40 UTC, dstrain115 commented on cirq-google/README.rst
> +<https://quantumai.google/cirq/google/concepts>`__. It also contains
This looks good to me.  What do you think of adjusting text for the other vendor modules as well?  We could do a much more simpler change, such as changing "this module contains everything you need for ..." to "this module contains all the code you need for...  See <the vendor> for more information on getting a license key for this service"

2025-01-16 02:44 UTC, pavoljuhas requested changes
LGTM with a couple of small suggestions - please see inline.
Thank you for improving these!

2025-01-16 02:44 UTC, pavoljuhas commented on cirq-web/README.rst
> +|cirq-web| is currently in development, and therefore is only available in
cirq-web is actually available as a "stable" package at https://pypi.org/project/cirq-web/ and it installs together with the cirq metapackage.  The installation info should be similar as for the other sub-packages.

2025-01-16 02:44 UTC, pavoljuhas commented on cirq-web/README.rst
> +
maybe remove these blanks?

2025-01-16 04:21 UTC, mhucka commented on cirq-aqt/README.rst
> +.. |cirq-core| replace:: ``cirq-core``
It is easier to achieve consistent formatting throughout a document when substitutions are defined. My experience is that when ``foo`` is used all over, sooner or later it's forgotten in some places, and the document starts to look sloppy. Also, it makes it easier to change or add formatting (such as hyperlinks). It's the same principle as defining macros for common terms in LaTeX. (I'm sure this is all familiar and I'm just overexplaining …)

2025-01-16 04:22 UTC, mhucka commented on cirq-aqt/README.rst
> +.. class:: centered
With respect, I don't think there's any need to match that page.

2025-01-16 04:23 UTC, mhucka commented on cirq-web/README.rst
> +|cirq-web| is currently in development, and therefore is only available in
Oh, woops, that text needs to be corrected!

2025-01-16 04:25 UTC, mhucka commented on cirq-web/README.rst
> +
I was using 2 blank lines before section headings, just as a convention. It's not uncommon if you all prefer single blank lines, that's okay with me.

2025-01-16 04:26 UTC, mhucka commented on cirq-aqt/README.rst
> +  name. Despite appearances, this will not install an old version 1.0 release!)
Yes, that's a good idea. (I think I only did it that way because the originals were as well. But it's better the way you suggest.

2025-01-16 04:27 UTC, mhucka commented on cirq-aqt/README.rst
> +.. |cirq-core| replace:: ``cirq-core``
That said, I'm not strongly bothered by getting rid of the substitutions and just doing ``foo``. These are short documents, after all.

2025-01-29 00:56 UTC, mhucka commented on cirq-aqt/README.rst
> +.. |cirq-core| replace:: ``cirq-core``
In the md format, I did away with this kind of thing and just used `foo`.

2025-01-29 00:58 UTC, mhucka commented on cirq-web/README.rst
> +
Turns out the Google Markdown convention does say 1 blank line, so in the Markdown version of the files, there is 1 blank line before and after section headings.

2025-01-29 00:59 UTC, mhucka commented on cirq-aqt/README.rst
> +  name. Despite appearances, this will not install an old version 1.0 release!)
Done in the Markdown version.

2025-01-29 01:00 UTC, mhucka commented on cirq-web/README.rst
> +|cirq-web| is currently in development, and therefore is only available in
Fixed in the Markdown version.

2025-01-29 04:27 UTC, mhucka commented on cirq-google/README.rst
> +<https://quantumai.google/cirq/google/concepts>`__. It also contains
@dstrain115 In the latest commit, I did as you suggested and updated the introductory paragraphs of the modules. Here's an example of what they look like now:

----

This is the Cirq-Pasqal integration module. It provides an interface that allows [Cirq](https:https://github.com/quantumlib/cirq) quantum algorithms to run on quantum computers made by [Pasqal](https://pasqal.com/). (See the [Documentation](#documentation) section below for information about getting access to Pasqal devices.)

----

What do you think of it?

2025-01-30 23:59 UTC, pavoljuhas approved these changes
Looks great, thank you for improving these!

Please correct URLs in cirq-google README before merging.

2025-01-30 23:59 UTC, pavoljuhas commented on cirq-google/README.md
> +| Google's quantum hardware is currently available only to authorized partners. Access requires an application, usually with a Google sponsor.|
Can we drop the UTF symbol?

2025-01-30 23:59 UTC, pavoljuhas commented on cirq-google/README.md
> +    guide](https://quantumai.google/cirq/tutorials/aqt/getting_started).
Please correct these links.

2025-01-31 19:18 UTC, mhucka commented on cirq-google/README.md
> +    guide](https://quantumai.google/cirq/tutorials/aqt/getting_started).
> Quote reply

Fixed in the upcoming next commit.

2025-01-31 19:19 UTC, mhucka commented
> Also, you may want to replace `README.rst` --> `README.md` in [docs/dev/modules.md](https://github.com/quantumlib/Cirq/blob/c51559aab35f947f744e5fb34a8ae7f1b6e5ca72/docs/dev/modules.md?plain=1)

I put that in the separate PR #7009. It could be argued that it would be better done in this PR. Should I move it?

2025-01-31 19:23 UTC, mhucka commented on cirq-google/README.md
> +| Google's quantum hardware is currently available only to authorized partners. Access requires an application, usually with a Google sponsor.|
OK.

2025-01-31 23:16 UTC, pavoljuhas commented
> I put that in the separate PR #7009. It could be argued that it would be better done in this PR. Should I move it here?

No need if already done.

The CI is failing because there are no `.rst` files anymore.

Can you please approve #7014 and resubmit after that?

2025-02-01 02:01 UTC, merged