Add support for conditional blocks in README.rst
quantumlib/Cirq pull request #6901
Opened 2024-12-31 04:44 UTC by mhucka

Due to differences in reStructuredText support between GitHub and PyPI, some basic things like centering images are impossible to do purely in RST in such a way that it works on both GitHub and PyPI. (This is not the case with Markdown; both PyPI and GitHub support some limited HTML inside Markdown, and that makes it possible to have the same Markdown README file work on both PyPI and GitHub.)

Since we are sticking with RST format for the top-level module README files, I wanted to have a way to create an attractive project README file for both GitHub and PyPI without having to keep two separate files. However, that meant solving the following problem.

PyPI supports RST's `.. class::` directive, but GitHub does not. PyPI also respects `:align:` attributes for images, but GitHub does not. Consequently, the only way to center text or images in RST for GitHub is to use raw HTML via the RST `.. raw::` directive, but it turns out that PyPI not only _doesn't support `raw`_ – it actually _throws an error and refuses your upload_ if your README file contains `.. raw::` constructs.

What to do? Well, we _can_ use `.. raw:: html` as long as we remove those constructs in the version of the file we save in the distribution for PyPI. Further, since GitHub simply ignores or strips out RST directives like `.. class::`, we can leave those constructs in the file that is sent to PYPI, and make use of them to do what we can't do in GitHub purely in RST. So, in summary:

1. Make the unmodified README.rst file work for GitHub, because that's what people will see when they visit the repo on GitHub.

2. Filter the README.rst file when producing distributions for PyPI, to remove content delimited by specific start and end markers that indicate parts that are valid on GitHub but not PyPI.

3. Use normal RST constructs that work on PyPI but not GitHub to accomplish what we can't do for GitHub without using raw HTML.

That's the approach is used in the new updated top-level README.rst file for Cirq, and it is enabled by this small modification to the `setup.py` file.

2025-01-14 03:16 UTC, dstrain115 commented
Do we actually still need this, since we dumped the cryostat image?

2025-01-15 21:36 UTC, dstrain115 commented
Another question.  There's no mandate for rst format.
Does switching to md format help, or does it just cause more problems?

2025-01-16 03:34 UTC, pavoljuhas commented
AFAICT this is so far only needed to support centered formatting in #6903.

TBH, I don't feel that centered format is worth the extra code to maintain and an extra complexity in the README.rst text and in setup.py.  If contributors do not pair up their markers correctly or manage to enter a different triangle symbol, they'd get a CI failure in which may be annoying.

Personally, the left-aligned default format looks good to me.
However, if there is a general opinion we need to have a centered one, we should check if markdown can do so without README filtering.

The current README.rst code is quite humanly readable in its plain text form.
I am afraid it would become much less so with conditional blocks and multi-line `.. raw:: html <div align="center">` markup.

2025-01-16 15:01 UTC, dstrain115 approved these changes

2025-01-16 15:01 UTC, dstrain115 commented
Yeah, I don't know if this is worth it for centered text, but I will leave it up to you.

2025-01-16 16:06 UTC, mhucka commented
Thank you for the feedback! 

GitHub comments lacks a good reply mechanism, so here I'll try to address multiple questions in one place.

From @dstrain115:

> Another question. There's no mandate for rst format. Does switching to md format help, or does it just cause more problems?

Switching to md would help and make things much simpler; in fact, I previously proposed using md in the (now-closed) PR #6805. However, in a chat conversation a couple of months ago, @pavoljuhas requested that the top-level README and the module README files be kept in rST format. I regret the time-limited chat history doesn't extend back far enough, so now I can't refer back to the details, but IIRC it was due to some issue with project descriptions on PyPI. I followed Pavol's request and kept rST.

PyPI accepts project descriptions in Markdown format, and both GitHub and PyPI respond to adding a subset of raw HTML into Markdown, so all the formatting that this rST stuff achieves could be done directly in Markdown. Doing so would avoid the need for the filtering code and those hacky comments-for-block-delimiters inside the files.

@pavol I'm sorry to have to ask, but could you re-explain the rST vs md problem?

From @pavol:

> AFAICT this is so far only needed to support centered formatting in #6903.

Yes, that's right. (Although the filtering mechanism is more general and could permit other things, the centering problem was the driver.)

> TBH, I don't feel that centered format is worth the extra code to maintain and an extra complexity in the README.rst text and in setup.py.

I agree it's a lot of work for centering. (I think Edvard Munch's painting _The Scream_ was actually the result of his frustrations in trying to make make an RST file work on both GitHub and PyPI.)

> If contributors do not pair up their markers correctly  or manage to enter a different triangle symbol, they'd get a CI failure which may be annoying.

If we switch to Markdownn, it would still require paired delimiters, but they would be simpler:

```markdown
<div align="center">

... stuff ...

</div>
```

Would this be easy enough for people?

(BTW, the comment string delimiter is arbitrary. I only picked those characters to make the strings unique, and assumed that people would simply copy-paste the things.)

> Personally, the left-aligned default format looks good to me.

I do accept that aesthetic judgements may differ. For myself, I find some other related projects' README files much more attractive (e.g., https://github.com/PennyLaneAI/pennylane) and am, well, saddened when I see Cirq's. It deserves better, so I'm trying hard to improve ours.

> The current README.rst is quite humanly readable in its plain text form. I am afraid it would become much less so with conditional blocks and multi-line `.. raw:: html <div align="center">` markup.

Yes, I agree the result is not as readable.

If the use of `<div align="center"> ... </div>` in Markdown is an acceptable compromise and if we can switch to md, then I'll close this PR and redo everything in md. (In that case, we should probably also convert the module readme's, yes? Then I should also close #6900.)

2025-01-16 19:40 UTC, pavoljuhas requested changes
@mhucka - I pushed the README from #6903 to temporary branches in my fork with and without the extra formatting markup and they render the same with the exception of centering of the top title and of the table in the Integrations section.

I also don't have a good recollection of our chat regarding the rst to markdown conversion in #6805;
perhaps my impression was there would be not much change in the README content and I was not convinced that the change of markup language is worth the effort.  (Note we'll need to also update all instances of "README.rst" in the docs and any setup scripts).  Now that #6903 makes significant changes to the README text, that point is moot.

If you feel strongly about centering and markdown can provide it out of the box we should go for it instead.

I'd strongly prefer to keep the README code simple and readable in its plain form and avoid custom conditionals and text post-processing.

Perhaps we could get there in these steps

1. close this PR (or limit it to fixups in setup.py)
2. finalize and merge #6903 without GitHub-only blocks
3. make a follow-up PR that would convert README.rst --> README.md (without text change) and update any dependent code and docs to use `README.md`

WDYT?

2025-01-27 21:12 UTC, mhucka commented
I will 

1. close this and PR #6903 
2. do another PR for a pure Markdown version of the top-level README
3. update the cirq-*/README PR to convert those to md too.

2025-01-27 21:12 UTC, closed without merging