Overhaul top-level README.rst file
quantumlib/Cirq pull request #6903
Opened 2024-12-31 20:52 UTC by mhucka

This is a major overhaul of the main Cirq README.rst file. Much of the content is rewritten, and there are numerous additions and enhancements all over. The changes include but are not limited to:

- Updates and corrections
- Addition of new sections
- Centering and resizing the logo for a more professional look
- Addition of GitHub badges for extra "pizzazz"
- Addition of a table of contents
- Addition of pointers to other Quantumlib software
- Improvements to info about how to cite Cirq

_Note_: this new README.rst depends on PRs #6902 and #6901 to be merged into main before this file will fully work.

Below is a screenshot of what the result will look like.

<div align="center">
<img width="80%" src="https://github.com/user-attachments/assets/64d84626-bb9e-4a7a-b6d7-0fcc4429d5d1">
</div>

2025-01-09 17:10 UTC, mhucka commented
Updated the README to account for changes requested by @dstrain115: removing the image of the quantum computer for now, and changing the description of Stim in the table in the Integrations section.

2025-01-14 03:15 UTC, dstrain115 approved these changes

2025-01-14 03:15 UTC, dstrain115 commented on README.rst
> +  meeting invitation.
Maybe a quick note that this is for group membership and we don't typically post messages there, in case people see no one has posted in forever.

2025-01-14 05:29 UTC, mhucka commented on README.rst
> +  meeting invitation.
Oh yes, that's a good point. I'll add a note.

2025-01-14 21:29 UTC, mhucka commented on README.rst
> +  meeting invitation.
Alright, I reworded this a little bit – how is it now?

2025-01-16 16:59 UTC, pavoljuhas requested changes
Please see inline.  I feel we should drop the conditional blocks also let us have a prominent link to the Cirq homepage.

2025-01-16 16:59 UTC, pavoljuhas commented on README.rst
> +.. |csl| image:: https://img.shields.io/badge/Download%20record-eeeeee.svg?style=flat-square&label=CSL&labelColor=2d98e0&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAUCAMAAADbT899AAAACXB
Do we truly need to include the base64 encoded PNG image in the link?
A shorter link 
https://img.shields.io/badge/Download%20record-eeeeee.svg?style=flat-square&labelColor=2d98e0
appears to work as well.

2025-01-16 16:59 UTC, pavoljuhas commented on README.rst
> +You should see the following output printed by Python:
Nit - the result `m` is random and will likely differ in user's run

```suggestion
You should see a similar output printed by Python:
```

2025-01-16 16:59 UTC, pavoljuhas commented on README.rst
> +Tutorials
The original README had a "Tutorials" link pointing to https://quantumai.google/cirq/build which is absent in the new version.  I feel that page is very useful for new users, because the tutorials there are categorized by subject and link to nicely rendered notebooks, no need to figure and run colabs at all.

Can we add a leading bullet point for these?  For example

* Tutorials at the Cirq homepage, for example, circuit building and circuit simulation tutorials under the [Build](https://quantumai.google/cirq/build) and [Simulate](https://quantumai.google/cirq/simula) tabs respectively.  Please other tabs for more tutorials.

2025-01-16 16:59 UTC, pavoljuhas commented on README.rst
> +------------------
The primary documentation source is the Cirq homepage (which seems to be missing).

Can we add it prominently as the first link in the Documentation?

2025-01-27 16:56 UTC, mhucka commented on README.rst
> +   :target: https://github.com/quantumlib/Cirq/blob/main/LICENSE
It's true that they duplicate some info. The following are some reasons why it's worth doing:

- When people link to the README page directly using the [`#README` target](https://github.com/quantumlib/Cirq#README), none of the GitHub top and right-hand side materials are visible when the page is first shown. Putting some notable things up top can help people quickly get some key info.
- On PyPI, I personally find it more time-consuming to locate info in PyPI's  left-hand sidebar because the content and layout of that sidebar changes with every project depending on various factors. Sometimes it's a fishing game to find, e.g., the license part. By contrast, the badge stuff stays in the same place (at the top), and because GitHub badges have become so popular with open-source projects, it's become a habit for me to look there first. (I have to believe I'm not the only person who does that ...)
- Also on PyPI, the GitHub stars and contributors items are not present (for obvious reasons).

That said, I do agree some of the badges could be removed.

2025-01-27 19:32 UTC, mhucka commented on README.rst
> +`Contact <#contact>`__
This is again for the benefit of reading the document on PyPI, and to a lesser extent on GitHub when links use the `#README` target. In addition, it may help people notice things that might be easy to miss otherwise, such as the "citing cirq" link.

Maybe I'm wrong, but the TOC seems to change very infrequently. Also, once we start applying a Markdown linter, broken links this will get flagged. Taken together, this seems unlikely to be a significant maintenance burden.

2025-01-27 19:32 UTC, mhucka commented on README.rst
> +You should see the following output printed by Python:
Will fix in the md version.

2025-01-27 19:51 UTC, mhucka commented on README.rst
> +------------------
Yes, good point! I'll add it in the md format.

I just now also filled in the URL field in the GitHub project settings, so there's a link there now:

![image](https://github.com/user-attachments/assets/d200eaa0-c2cd-41d3-b133-7ed4e39d6897)

2025-01-27 20:01 UTC, mhucka commented on README.rst
> +.. |csl| image:: https://img.shields.io/badge/Download%20record-eeeeee.svg?style=flat-square&label=CSL&labelColor=2d98e0&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAUCAMAAADbT899AAAACXB
It's to get an icon into the badge. Adding a little pizzazz helps our readme page stand out :-).

A BibTeX/LaTeX icon exists in shields.io, but the others don't, so I created custom graphics based on icons I could find elsewhere for CSL and Marc21. The base64 encoding is the only way to get the icons into the badges. 

I guess a better solution would be to submit the icons to shields.io, and then we can link to them. So, fine, I'll take out the base64 stuff for now. When there's a better solution, we can add that.

2025-01-27 20:04 UTC, mhucka commented on README.rst
> +Tutorials
I think what happened is that it seemed like the /start/basics link would be an easier starting point for new people. We can add this, though – your text provides good info.

2025-01-27 21:13 UTC, closed without merging